services:
  web:
    build: .
    container_name: flask_web_app
    restart: unless-stopped
    ports:
      - "443:443"
    mem_limit: 2g # Added to prevent OOM errors during testing, pending SECRET_KEY fix
    environment: # Explicitly define environment variables
      SECRET_KEY: ${SECRET_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MONGO_URI: mongodb://mongo:27017/appdb
      RATELIMIT_STORAGE_URI: redis://redis:6379/0
      DOCKER_CONTAINER: "true"
      FLASK_APP: main.py
      FLASK_ENV: ${FLASK_ENV} # Will be set to 'development' or 'production' by calling environment
    volumes:
      - ./certs:/app/certs:ro # Mount certs for HTTPS
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started

  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
