services:
  # The Cloudflare Tunnel connector for Staging
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${STAGING_TOKEN}
    depends_on:
      nginx:
        condition: service_started
