services:
  web:
    build: .
    container_name: flask_web_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
      - DOCKER_CONTAINER=true
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
