name: Deploy to Production (Raspberry Pi)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-pi:
    runs-on: self-hosted # This will use your pi-prod labeled runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          ./scripts/deploy.sh
          docker system prune -f
