name: Deploy to Production (Raspberry Pi)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-pi:
    runs-on: self-hosted # This will use your pi-prod labeled runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          LOG_LEVEL: INFO
        run: |
          ./scripts/deploy.sh
          docker system prune -f

      - name: Create Admin User
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          echo "Attempting to create admin user..."
          docker compose exec -T \
            -e ADMIN_USERNAME="$ADMIN_USERNAME" \
            -e ADMIN_PASSWORD="$ADMIN_PASSWORD" \
            web python scripts/create_admin.py
