name: Test and Deploy to WSL

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Using a GitHub-hosted runner for build and test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Adjust to your project's Python version

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Run tests in container
        run: docker compose exec -e PYTHONPATH=/app web /app/.venv/bin/pytest

      - name: Stop containers
        if: always()
        run: docker compose down

  deploy-to-wsl:
    needs: build-and-test
    runs-on: self-hosted # This will use your wsl-test labeled runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to WSL
        run: |
          ./scripts/deploy.sh
          docker system prune -f
