name: Test and Deploy to WSL

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: pip install poetry && poetry install

      # - name: Run Linting
      #   run: poetry run flake8 src tests

      # - name: Check Code Formatting
      #   run: poetry run black --check src tests

      

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: |
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          export LOG_LEVEL=INFO
          docker compose up -d

      

      - name: Stop containers
        if: always()
        run: docker compose down

  deploy-to-wsl:
    needs: build-and-test
    runs-on: LAPTOP-DGQCFFFI # Explicitly target the runner by its name
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run database connection test
        run: |
          docker compose exec -e PYTHONPATH=/app web /app/.venv/bin/pytest tests/test_database_connection.py

      - name: Deploy to WSL
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          LOG_LEVEL: INFO
        run: |
          ./scripts/deploy.sh
          docker system prune -f

      - name: Create Admin User
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          echo "Attempting to create admin user..."
          docker compose exec -T \
            -e ADMIN_USERNAME="$ADMIN_USERNAME" \
            -e ADMIN_PASSWORD="$ADMIN_PASSWORD" \
            web python scripts/create_admin.py
